const items = [
  {
    id: 1,
    author: 'Paul',
    date: 'Oct 25, 2019',
    avi: require('../assets/images/paul.png'),
    category: 'Food Delivery',
    type: 'buying',
    content: 'Looking for someome to bring me a foot-long Subway, no onions no pickles no olives, around noon today at my office',
    proposed_price: 3, //proposed service price
  },
  {
    id: 2,
    author: 'Madeline',
    date: 'Oct 25, 2019',
    avi: require('../assets/images/madeline.png'),
    category: 'Transportation',
    type: 'buying',
    content: 'Looking for a ride from SD to LA on 10/30 at 7pm. Pick me up at PC Loop',
    proposed_price: 25, 
  },
  {
    id: 3,
    author: 'Gary',
    date: 'Oct 25, 2019',
    avi: require('../assets/images/gary.png'),
    category: 'Other',
    type: 'buying',
    content: 'Hello everyone, I am looking for a personal trainer every Sunday at 5pm. Each workout session willing to pay $50.',
    proposed_price: 50, 
  },
  {
    id: 4,
    author: 'Jessica',
    date: 'Oct 25, 2019',
    avi: require('../assets/images/jessica.png'),
    category: 'Career',
    type: 'selling',
    content: 'CES is providing mock interview sessions aiming for the Big Four, 10/1 11am ~ 3pm, at Geisel Library 7th floor',
    proposed_price: 20, 
  },
  {
    id: 5,
    author: 'Cheng',
    date: 'Oct 25, 2019',
    avi: require('../assets/images/cheng.png'),
    category: 'Learning & Skills',
    type: 'selling',
    content: 'My goal is to spread my knowledge and skills to people for free, including deep learning, NLP, and ML algorithm.',
    proposed_price: 0, 
  },
  {
    id: 6,
    author: 'Charles',
    date: 'Oct 25, 2019',
    avi: require('../assets/images/charles.png'),
    category: 'Learning & Skills',
    type: 'selling',
    content: 'Imma teach you how to answer every single Piazza post as a tutor and be to able to play Pokemon Go at the same time',
    proposed_price: 0, 
  },
  {
    id: 7,
    author: 'Paul',
    date: 'Oct 25, 2019',
    avi: require('../assets/images/paul.png'),
    category: 'Food Delivery',
    type: 'buying',
    content: 'Looking for someome to bring me a foot-long Subway, no onions no pickles no olives, around noon today at my office',
    proposed_price: 3, //proposed service price
  },
  {
    id: 8,
    author: 'Madeline',
    date: 'Oct 25, 2019',
    avi: require('../assets/images/madeline.png'),
    category: 'Transportation',
    type: 'buying',
    content: 'Looking for a ride from SD to LA on 10/30 at 7pm. Pick me up at PC Loop',
    proposed_price: 25, 
  },
  {
    id: 9,
    author: 'Gary',
    date: 'Oct 25, 2019',
    avi: require('../assets/images/gary.png'),
    category: 'Other',
    type: 'buying',
    content: 'Hello everyone, I am looking for a personal trainer every Sunday at 5pm. Each workout session willing to pay $50.',
    proposed_price: 50, 
  },
  {
    id: 10,
    author: 'Jessica',
    date: 'Oct 25, 2019',
    avi: require('../assets/images/jessica.png'),
    category: 'Career',
    type: 'selling',
    content: 'CES is providing mock interview sessions aiming for the Big Four at this 10/1 11am ~ 3pm at Geisel Library 7th floor',
    proposed_price: 20, 
  },
  {
    id: 11,
    author: 'Cheng',
    date: 'Oct 25, 2019',
    avi: require('../assets/images/cheng.png'),
    category: 'Learning & Skills',
    type: 'selling',
    content: 'My goal is to spread my knowledge and skills to people for free, including deep learning, NLP, and ML algorithm.',
    proposed_price: 0, 
  },
  {
    id: 12,
    author: 'Charles',
    date: 'Oct 25, 2019',
    avi: require('../assets/images/charles.png'),
    category: 'Learning & Skills',
    type: 'selling',
    content: 'Imma teach you how to answer every single Piazza post as a tutor and be to able to play Pokemon Go at the same time',
    proposed_price: 100, 
  },
];

const profile = {
  firstname: 'Madeline',
  lastname: 'Lee',
  displayname: 'Madeline',
  email: 'audimadeline@gmail.com',
  password: 'CSE110isFun',
  avatar: require('../assets/images/avatar.png'),
  uid: '123',
};

export {
  items,
  profile,
}